# Imports

In [1]:
import sys
import os
sys.path.append(os.path.dirname(os.getcwd()))

from utils import data_prep_utils
import pandas

In [7]:
os.path.join(os.path.dirname(os.getcwd()), "medical_genomics_2021_data", "u")

'c:\\Users\\yaelz\\OneDrive - mail.tau.ac.il\\school_dev\\workShop\\workshop_genomic\\medical_genomics_2021_data\\u'

# Test get_df

In [2]:
dfs = {}

for table_name in os.listdir(os.path.join(os.path.dirname(os.getcwd()), "medical_genomics_2021_data")):
    dfs[table_name] = data_prep_utils.get_df(table_name)

print(dfs.keys())

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\Users\\yaelz\\OneDrive - mail.tau.ac.il\\school_dev\\workShop\\workshop_genomic\\noteboot_tests\\medical_genomics_2021_data'

In [4]:
dfs["beat_drug"].head()

,12-00066,12-00150,12-00211,12-00258,12-00294,12-00372,13-00028,13-00034,13-00098,13-00118,...,16-01102,16-01138,16-01151,16-01185,16-01216,16-01219,16-01227,16-01237,16-01262,16-01270
A-674563,0.302313,0.183573,10.0,2.250759,0.312102,1.112644,3.699257,1.522665,5.132768,1.83987,...,0.726144,0.454933,0.103835,0.192891,0.515219,0.531155,1.261865,0.674077,0.518016,0.259479
Afatinib (BIBW-2992),0.270839,0.095105,10.0,1.042656,0.412103,0.492191,1.126676,0.313330,4.442185,1.09213,...,1.146014,1.047075,0.556972,0.615777,0.456265,0.809377,1.279045,0.983270,2.017039,1.303088
Alisertib (MLN8237),2.292925,10.000000,10.0,10.000000,1.731348,6.149094,10.000000,10.000000,10.000000,10.00000,...,10.000000,10.000000,2.080804,8.928137,6.927002,9.425326,4.785701,10.000000,10.000000,10.000000
Axitinib (AG-013736),0.137656,10.000000,10.0,10.000000,0.124162,10.000000,10.000000,10.000000,10.000000,10.00000,...,10.000000,10.000000,10.000000,10.000000,0.418123,10.000000,10.000000,10.000000,10.000000,0.299026
AZD1480,2.429158,NaN,10.0,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.00000,...,10.000000,6.874162,10.000000,10.000000,3.607693,7.004078,10.000000,10.000000,10.000000,10.000000

In [5]:
dfs["beat_rnaseq"].iloc[:, 2].sum()

999999.9999998771

In [6]:
dfs["drug_mut_cor"].head()

,Trametinib (GSK1120212),Vandetanib (ZD6474),Foretinib (XL880),Selumetinib (AZD6244),Pazopanib (GW786034),Linifanib (ABT-869),Ponatinib (AP24534),Bosutinib (SKI-606),Nilotinib,PD173955,...,Midostaurin,KW-2449,VX-745,Doramapimod (BIRB 796),Sunitinib,A-674563,STO609,Motesanib (AMG-706),RAF265 (CHIR-265),Lapatinib
DNMT3A,0.069469,-0.037514,-0.051905,0.057819,-0.139401,-0.108668,-0.029188,0.043266,0.078163,0.008499,...,-0.058874,-0.068247,0.161595,0.049790,-0.066416,0.080100,0.035998,-0.000191,0.046545,-0.051173
IDH1,0.063324,-0.008074,0.080502,0.108843,-0.060474,0.112876,-0.058486,0.087434,0.084876,0.054812,...,0.098229,0.071768,0.029620,0.173868,0.040351,0.027222,-0.061539,-0.056941,0.042370,-0.076427
NPM1,0.035875,-0.137700,-0.298134,0.062277,-0.164032,-0.116955,-0.235712,0.017500,0.173132,-0.100239,...,-0.017841,-0.214955,-0.132103,-0.049234,-0.244746,-0.170908,0.122385,0.084865,-0.077006,-0.091174
IDH2,0.178590,-0.006413,0.016696,0.212272,-0.030986,0.184596,-0.037989,0.093351,0.156715,-0.083524,...,0.154489,-0.054508,-0.079835,-0.113794,-0.013196,-0.098377,-0.030367,0.149168,-0.029779,0.111125
RUNX1,-0.010058,-0.021164,0.015147,-0.013067,-0.038516,-0.004423,0.001642,-0.069553,-0.094509,-0.004865,...,-0.170115,-0.059335,-0.022117,-0.038665,0.037304,0.053678,0.112679,-0.067360,0.055343,0.071343

In [7]:
dfs["drug_mut_cor_labels"].head()

   12-00372
0  13-00098
1  13-00118
2  13-00149
3  13-00160
4  13-00163

In [8]:
dfs["tcga_mut"].head()

,TCGA.AB.2803,TCGA.AB.2805,TCGA.AB.2806,TCGA.AB.2807,TCGA.AB.2808,TCGA.AB.2810,TCGA.AB.2811,TCGA.AB.2812,TCGA.AB.2813,TCGA.AB.2814,...,TCGA.AB.3000,TCGA.AB.3001,TCGA.AB.3002,TCGA.AB.3005,TCGA.AB.3006,TCGA.AB.3007,TCGA.AB.3008,TCGA.AB.3009,TCGA.AB.3011,TCGA.AB.3012
DNMT3A,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
IDH1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
NPM1,False,False,False,False,False,True,True,True,False,False,...,False,False,False,False,False,False,False,False,True,False
IDH2,False,True,False,True,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
RUNX1,False,True,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [9]:
dfs["tcga_rna"].iloc[:, 2].sum()

999999.9999999999

# Test trranspose_df

In [10]:
dfs_t = {}
to_be_transposed = dfs.keys() - ['drug_mut_cor', 'drug_mut_cor_labels']
for table_name in to_be_transposed:
    dfs_t[table_name] = data_prep_utils.transpose_df(dfs[table_name])
print(dfs_t.keys())

dict_keys(['tcga_mut', 'tcga_rna', 'beat_rnaseq', 'beat_drug'])

In [11]:
dfs_t["beat_drug"].head()

,A-674563,Afatinib (BIBW-2992),Alisertib (MLN8237),Axitinib (AG-013736),AZD1480,Barasertib (AZD1152-HQPA),BEZ235,BMS-345541,Bortezomib (Velcade),Bosutinib (SKI-606),...,TG100-115,Tofacitinib (CP-690550),Tozasertib (VX-680),Trametinib (GSK1120212),Vandetanib (ZD6474),Vargetef,Vatalanib (PTK787),Vismodegib (GDC-0449),VX-745,YM-155
12-00066,0.302313,0.270839,2.292925,0.137656,2.429158,10.0,0.038276,1.246408,0.180191,0.325536,...,3.179477,7.402374,1.980158,0.013717,1.644795,0.046360,1.226845,NaN,0.078243,0.217887
12-00150,0.183573,0.095105,10.000000,10.000000,NaN,10.0,10.000000,0.790187,0.100763,0.699443,...,10.000000,10.000000,10.000000,10.000000,3.394143,0.889183,2.569394,NaN,10.000000,0.635149
12-00211,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,10.000000,7.731091,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,1.000000
12-00258,2.250759,1.042656,10.000000,10.000000,10.000000,10.0,3.249688,3.275260,2.044805,10.000000,...,10.000000,0.013717,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,1.000000
12-00294,0.312102,0.412103,1.731348,0.124162,10.000000,10.0,0.025282,0.950431,0.481923,0.293284,...,10.000000,1.759087,0.729700,0.013717,7.220722,0.169410,3.877601,10.0,0.553480,0.978179

In [12]:
dfs_t["beat_rnaseq"].head()

,TSPAN6,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,STPG1,...,RP11-218F10.3,RP11-686O6.2,RP11-313P22.1,RP11-548H3.1,RP11-102N12.3,RP11-196O16.1,RP4-671G15.2,RP11-731C17.2,RP4-621B10.8,RP11-114I8.4
12-00066,0.070215,23.311415,10.532266,11.129094,906.792960,4.739520,43.849332,44.340838,57.435955,4.177799,...,0.491506,0.140430,0.210645,1.509625,0.210645,0.315968,0.105323,1.298979,0.035108,0.561721
12-00150,1.709459,32.137834,17.778376,11.253940,49.004499,8.262386,84.589743,39.346054,32.052361,10.199774,...,0.142455,0.626802,0.142455,1.310585,1.481531,1.082658,0.000000,0.626802,0.000000,0.170946
12-00211,0.000000,25.117470,37.659392,12.541923,111.834945,2.118341,59.078171,67.349788,77.470749,7.767250,...,1.513101,0.302620,0.134498,2.051092,0.067249,0.975109,0.067249,2.622708,0.369869,1.613974
12-00258,0.000000,29.351673,15.647852,8.190423,1004.458236,30.403362,30.020930,44.011575,51.692089,5.035358,...,0.286824,0.828603,0.127477,2.645156,0.573648,0.350563,0.063739,0.956081,0.382432,0.223085
12-00294,0.000000,31.240770,39.189992,18.875313,267.852800,2.388038,37.325360,56.429663,60.060789,6.379005,...,1.962771,0.196277,0.228990,2.224474,0.425267,0.032713,0.228990,4.710650,0.817821,0.883247

In [13]:
dfs_t["tcga_mut"].head()

,DNMT3A,IDH1,NPM1,IDH2,RUNX1,NRAS,CEBPA,FLT3,TP53,TET2,WT1
TCGA.AB.2803,False,False,False,False,False,False,False,False,False,False,False
TCGA.AB.2805,False,False,False,True,True,False,False,False,False,False,False
TCGA.AB.2806,False,False,False,False,False,False,False,False,False,False,False
TCGA.AB.2807,False,False,False,True,True,False,False,False,False,False,False
TCGA.AB.2808,False,False,False,False,False,True,True,False,False,False,False

In [14]:
dfs_t["tcga_rna"].head()

,A1BG,A1CF,A2BP1,A2LD1,A2M,A2ML1,A4GALT,A4GNT,AAA1,AAAS,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
TCGA.AB.2803,21.786275,0.0,0.0,3.772166,24.673141,0.108692,0.597809,0.000000,0.0,27.173063,...,21.150422,13.043071,1.739075,23.857949,179.831328,0.815192,58.530777,236.677376,131.463275,63.367583
TCGA.AB.2805,5.251160,0.0,0.0,3.007237,0.995091,0.207309,0.041459,0.165849,0.0,33.003750,...,34.532453,23.301644,0.746316,22.057779,249.020739,0.165849,109.915751,358.065790,237.038225,70.982935
TCGA.AB.2806,10.866631,0.0,0.0,2.951634,0.406560,0.332639,1.034880,0.073922,0.0,29.272380,...,42.643793,25.650289,3.917765,47.937217,221.649567,0.110880,43.502006,317.487043,213.666193,112.913030
TCGA.AB.2807,18.869409,0.0,0.0,2.491801,18.714176,0.054085,6.328205,0.270434,0.0,37.969229,...,35.305970,39.321409,8.275342,49.597978,140.518592,0.270434,65.715969,192.983193,229.275720,75.938453
TCGA.AB.2808,8.199836,0.0,0.0,2.934105,15.931201,0.342311,11.345199,0.048899,0.0,27.629468,...,55.243286,48.119281,2.493984,31.541600,192.037017,0.097804,98.488047,225.779196,180.007197,89.147819

# Test get_data_reorgenized

In [15]:
drugs_reorg = data_prep_utils.get_data_reorgenized(dfs_t["beat_rnaseq"], dfs_t["beat_drug"])

In [16]:
print(f"drugs transposed shape: {dfs_t['beat_drug'].shape}\ndrugs re shape: {drugs_reorg.shape}")
drugs_reorg.head()

drugs transposed shape: (198, 79)
drugs re shape: (198, 79)

,A-674563,Afatinib (BIBW-2992),Alisertib (MLN8237),Axitinib (AG-013736),AZD1480,Barasertib (AZD1152-HQPA),BEZ235,BMS-345541,Bortezomib (Velcade),Bosutinib (SKI-606),...,TG100-115,Tofacitinib (CP-690550),Tozasertib (VX-680),Trametinib (GSK1120212),Vandetanib (ZD6474),Vargetef,Vatalanib (PTK787),Vismodegib (GDC-0449),VX-745,YM-155
12-00066,0.302313,0.270839,2.292925,0.137656,2.429158,10.0,0.038276,1.246408,0.180191,0.325536,...,3.179477,7.402374,1.980158,0.013717,1.644795,0.046360,1.226845,NaN,0.078243,0.217887
12-00150,0.183573,0.095105,10.000000,10.000000,NaN,10.0,10.000000,0.790187,0.100763,0.699443,...,10.000000,10.000000,10.000000,10.000000,3.394143,0.889183,2.569394,NaN,10.000000,0.635149
12-00211,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,10.000000,7.731091,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,1.000000
12-00258,2.250759,1.042656,10.000000,10.000000,10.000000,10.0,3.249688,3.275260,2.044805,10.000000,...,10.000000,0.013717,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,1.000000
12-00294,0.312102,0.412103,1.731348,0.124162,10.000000,10.0,0.025282,0.950431,0.481923,0.293284,...,10.000000,1.759087,0.729700,0.013717,7.220722,0.169410,3.877601,10.0,0.553480,0.978179

In [17]:
mut_reorg = data_prep_utils.get_data_reorgenized(dfs_t["tcga_rna"], dfs_t["tcga_mut"])

In [18]:
print(f"muts transposed shape: {dfs_t['tcga_mut'].shape}\nmuts re shape: {mut_reorg.shape}")
mut_reorg.head()

muts transposed shape: (167, 11)
muts re shape: (167, 11)

,DNMT3A_y,IDH1_y,NPM1_y,IDH2_y,RUNX1_y,NRAS_y,CEBPA_y,FLT3_y,TP53_y,TET2_y,WT1_y
TCGA.AB.2803,False,False,False,False,False,False,False,False,False,False,False
TCGA.AB.2805,False,False,False,True,True,False,False,False,False,False,False
TCGA.AB.2806,False,False,False,False,False,False,False,False,False,False,False
TCGA.AB.2807,False,False,False,True,True,False,False,False,False,False,False
TCGA.AB.2808,False,False,False,False,False,True,True,False,False,False,False

# Test filter_beat_by_tcga

In [19]:
beat_filt = data_prep_utils.filter_beat_by_tcga(dfs["beat_rnaseq"], dfs["tcga_rna"])

In [20]:
print(f"{dfs['beat_rnaseq'].shape}\n{beat_filt.shape}")

(22843, 198)
(14187, 198)

In [21]:
beat_filt.head()

,12-00066,12-00150,12-00211,12-00258,12-00294,12-00372,13-00028,13-00034,13-00098,13-00118,...,16-01102,16-01138,16-01151,16-01185,16-01216,16-01219,16-01227,16-01237,16-01262,16-01270
TSPAN6,0.070215,1.709459,0.000000,0.000000,0.000000,0.921085,0.000000,0.000000,0.000000,0.115955,...,0.052768,0.271781,0.118997,0.164221,0.648789,0.085224,0.395749,0.249059,0.142059,0.150957
DPM1,23.311415,32.137834,25.117470,29.351673,31.240770,22.940781,28.176101,34.303196,39.203413,24.089688,...,21.089525,25.547442,26.208989,32.023086,34.238344,28.607021,25.101824,38.785308,33.703438,16.575035
SCYL3,10.532266,17.778376,37.659392,15.647852,39.189992,33.734750,23.989937,17.804722,15.450059,25.510139,...,6.842223,34.244444,30.433366,26.234297,13.477109,20.823184,17.950065,7.245358,16.461058,16.212740
C1orf112,11.129094,11.253940,12.541923,8.190423,18.875313,11.110592,12.907338,6.758411,23.516117,12.465182,...,8.864988,24.520713,14.755571,13.219787,5.721136,16.874449,6.105849,4.845333,8.647826,6.944004
FGR,906.792960,49.004499,111.834945,1004.458236,267.852800,170.631056,68.186164,619.473686,11.031520,201.790997,...,451.393235,187.045931,102.961759,186.329197,583.113507,22.300408,24.508199,77.751751,45.565344,51.898882

In [22]:
beat_filt_trans = data_prep_utils.transpose_df(beat_filt)

In [23]:
beat_filt_trans.head()

,TSPAN6,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,NIPAL3,...,TERC,TSIX,SRXN1,SNORD11B,GTF2H5,NUDT3,SNORA28,DOC2B,SNURF,DGCR11
12-00066,0.070215,23.311415,10.532266,11.129094,906.792960,4.739520,43.849332,44.340838,57.435955,25.207222,...,0.105323,0.000000,1.053227,0.035108,10.181190,246.770983,0.280860,8.109845,0.070215,2.457529
12-00150,1.709459,32.137834,17.778376,11.253940,49.004499,8.262386,84.589743,39.346054,32.052361,23.020718,...,0.256419,0.000000,0.769257,0.028491,7.721058,161.116537,0.113964,0.455856,0.284910,1.851914
12-00211,0.000000,25.117470,37.659392,12.541923,111.834945,2.118341,59.078171,67.349788,77.470749,71.250225,...,0.235371,1.513101,0.638865,0.033624,11.196944,274.644567,0.605240,3.900437,0.235371,2.622708
12-00258,0.000000,29.351673,15.647852,8.190423,1004.458236,30.403362,30.020930,44.011575,51.692089,28.299985,...,0.223085,0.223085,1.402251,0.000000,11.887268,106.475505,0.223085,0.350563,0.159347,1.784684
12-00294,0.000000,31.240770,39.189992,18.875313,267.852800,2.388038,37.325360,56.429663,60.060789,43.671652,...,0.163564,0.000000,0.032713,0.130851,11.842051,272.759727,0.130851,0.000000,0.327128,1.995484

In [24]:
drugs_reorg_filt = data_prep_utils.get_data_reorgenized(beat_filt_trans, dfs_t["beat_drug"])

In [25]:
print(f"{drugs_reorg.shape}\n{drugs_reorg_filt.shape}")
drugs_reorg_filt.head()

(198, 79)
(198, 79)

,A-674563,Afatinib (BIBW-2992),Alisertib (MLN8237),Axitinib (AG-013736),AZD1480,Barasertib (AZD1152-HQPA),BEZ235,BMS-345541,Bortezomib (Velcade),Bosutinib (SKI-606),...,TG100-115,Tofacitinib (CP-690550),Tozasertib (VX-680),Trametinib (GSK1120212),Vandetanib (ZD6474),Vargetef,Vatalanib (PTK787),Vismodegib (GDC-0449),VX-745,YM-155
12-00066,0.302313,0.270839,2.292925,0.137656,2.429158,10.0,0.038276,1.246408,0.180191,0.325536,...,3.179477,7.402374,1.980158,0.013717,1.644795,0.046360,1.226845,NaN,0.078243,0.217887
12-00150,0.183573,0.095105,10.000000,10.000000,NaN,10.0,10.000000,0.790187,0.100763,0.699443,...,10.000000,10.000000,10.000000,10.000000,3.394143,0.889183,2.569394,NaN,10.000000,0.635149
12-00211,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,10.000000,7.731091,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,1.000000
12-00258,2.250759,1.042656,10.000000,10.000000,10.000000,10.0,3.249688,3.275260,2.044805,10.000000,...,10.000000,0.013717,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,1.000000
12-00294,0.312102,0.412103,1.731348,0.124162,10.000000,10.0,0.025282,0.950431,0.481923,0.293284,...,10.000000,1.759087,0.729700,0.013717,7.220722,0.169410,3.877601,10.0,0.553480,0.978179