# Imports

In [1]:
import data_prep_utils
import norm_utils

# Test sum_gene_exp_to_num (1)

In [2]:
beat_rna = data_prep_utils.get_df("beat_rnaseq")
tcga_rna = data_prep_utils.get_df("tcga_rna")
beat_rna_t = data_prep_utils.transpose_df(beat_rna)
tcga_rna_t = data_prep_utils.transpose_df(tcga_rna)

In [3]:
beat_rna_t.head()

,TSPAN6,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,STPG1,...,RP11-218F10.3,RP11-686O6.2,RP11-313P22.1,RP11-548H3.1,RP11-102N12.3,RP11-196O16.1,RP4-671G15.2,RP11-731C17.2,RP4-621B10.8,RP11-114I8.4
12-00066,0.070215,23.311415,10.532266,11.129094,906.792960,4.739520,43.849332,44.340838,57.435955,4.177799,...,0.491506,0.140430,0.210645,1.509625,0.210645,0.315968,0.105323,1.298979,0.035108,0.561721
12-00150,1.709459,32.137834,17.778376,11.253940,49.004499,8.262386,84.589743,39.346054,32.052361,10.199774,...,0.142455,0.626802,0.142455,1.310585,1.481531,1.082658,0.000000,0.626802,0.000000,0.170946
12-00211,0.000000,25.117470,37.659392,12.541923,111.834945,2.118341,59.078171,67.349788,77.470749,7.767250,...,1.513101,0.302620,0.134498,2.051092,0.067249,0.975109,0.067249,2.622708,0.369869,1.613974
12-00258,0.000000,29.351673,15.647852,8.190423,1004.458236,30.403362,30.020930,44.011575,51.692089,5.035358,...,0.286824,0.828603,0.127477,2.645156,0.573648,0.350563,0.063739,0.956081,0.382432,0.223085
12-00294,0.000000,31.240770,39.189992,18.875313,267.852800,2.388038,37.325360,56.429663,60.060789,6.379005,...,1.962771,0.196277,0.228990,2.224474,0.425267,0.032713,0.228990,4.710650,0.817821,0.883247

In [4]:
tcga_rna_t.head()

,A1BG,A1CF,A2BP1,A2LD1,A2M,A2ML1,A4GALT,A4GNT,AAA1,AAAS,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
TCGA.AB.2803,21.786275,0.0,0.0,3.772166,24.673141,0.108692,0.597809,0.000000,0.0,27.173063,...,21.150422,13.043071,1.739075,23.857949,179.831328,0.815192,58.530777,236.677376,131.463275,63.367583
TCGA.AB.2805,5.251160,0.0,0.0,3.007237,0.995091,0.207309,0.041459,0.165849,0.0,33.003750,...,34.532453,23.301644,0.746316,22.057779,249.020739,0.165849,109.915751,358.065790,237.038225,70.982935
TCGA.AB.2806,10.866631,0.0,0.0,2.951634,0.406560,0.332639,1.034880,0.073922,0.0,29.272380,...,42.643793,25.650289,3.917765,47.937217,221.649567,0.110880,43.502006,317.487043,213.666193,112.913030
TCGA.AB.2807,18.869409,0.0,0.0,2.491801,18.714176,0.054085,6.328205,0.270434,0.0,37.969229,...,35.305970,39.321409,8.275342,49.597978,140.518592,0.270434,65.715969,192.983193,229.275720,75.938453
TCGA.AB.2808,8.199836,0.0,0.0,2.934105,15.931201,0.342311,11.345199,0.048899,0.0,27.629468,...,55.243286,48.119281,2.493984,31.541600,192.037017,0.097804,98.488047,225.779196,180.007197,89.147819

In [5]:
beat_rna_sum_1 = norm_utils.sum_gene_exp_to_num(beat_rna_t, 1)

AttributeError: module 'norm_utils' has no attribute 'sum_gene_exp_to_num'

In [ ]:
for i in range(1, 5):
    print(beat_rna_sum_1.iloc[:, i].sum())
beat_rna_sum_1.head()

1.0
1.0
0.9999999999999998
0.9999999999999998

,SampleID,TSPAN6,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,RP11-218F10.3,RP11-686O6.2,RP11-313P22.1,RP11-548H3.1,RP11-102N12.3,RP11-196O16.1,RP4-671G15.2,RP11-731C17.2,RP4-621B10.8,RP11-114I8.4
0,12-00066,0.000782,0.003928,0.002632,0.004891,0.013171,0.001509,0.004782,0.004736,0.004720,...,0.003404,0.001028,0.006223,0.004159,0.002921,0.002092,0.004358,0.002713,0.001219,0.004699
1,12-00150,0.019045,0.005416,0.004442,0.004945,0.000712,0.002631,0.009225,0.004203,0.002634,...,0.000987,0.004590,0.004208,0.003611,0.020541,0.007167,0.000000,0.001309,0.000000,0.001430
2,12-00211,0.000000,0.004233,0.009410,0.005511,0.001624,0.000674,0.006443,0.007194,0.006366,...,0.010479,0.002216,0.003973,0.005651,0.000932,0.006455,0.002783,0.005478,0.012841,0.013501
3,12-00258,0.000000,0.004946,0.003910,0.003599,0.014590,0.009680,0.003274,0.004701,0.004248,...,0.001986,0.006068,0.003766,0.007287,0.007953,0.002321,0.002637,0.001997,0.013277,0.001866
4,12-00294,0.000000,0.005265,0.009793,0.008295,0.003891,0.000760,0.004071,0.006027,0.004936,...,0.013594,0.001437,0.006765,0.006128,0.005896,0.000217,0.009475,0.009839,0.028393,0.007389

In [ ]:
tcga_rna_sum_1 = norm_utils.sum_gene_exp_to_num(tcga_rna_t, 1)

In [ ]:
for i in range(1, 5):
    print(tcga_rna_sum_1.iloc[:, i].sum())
tcga_rna_sum_1.head()

1.0
1.0
1.0
1.0

,SampleID,A1BG,A1CF,A2BP1,A2LD1,A2M,A2ML1,A4GALT,A4GNT,AAA1,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
0,TCGA.AB.2803,0.012028,0.0,0.0,0.006236,0.017993,0.001416,0.000889,0.000000,0.0,...,0.003914,0.002194,0.002381,0.004551,0.005147,0.020104,0.005412,0.002941,0.003577,0.004913
1,TCGA.AB.2805,0.002899,0.0,0.0,0.004972,0.000726,0.002700,0.000062,0.009349,0.0,...,0.006391,0.003919,0.001022,0.004207,0.007127,0.004090,0.010163,0.004449,0.006449,0.005503
2,TCGA.AB.2806,0.005999,0.0,0.0,0.004880,0.000296,0.004333,0.001540,0.004167,0.0,...,0.007892,0.004315,0.005365,0.009144,0.006343,0.002734,0.004022,0.003945,0.005813,0.008754
3,TCGA.AB.2807,0.010418,0.0,0.0,0.004120,0.013647,0.000705,0.009415,0.015245,0.0,...,0.006534,0.006614,0.011331,0.009460,0.004021,0.006669,0.006076,0.002398,0.006238,0.005887
4,TCGA.AB.2808,0.004527,0.0,0.0,0.004851,0.011618,0.004459,0.016879,0.002756,0.0,...,0.010224,0.008094,0.003415,0.006016,0.005496,0.002412,0.009106,0.002805,0.004897,0.006912

# Test sum_gene_exp_to_num (mill)

In [ ]:
beat_rna_sum_mil = norm_utils.sum_gene_exp_to_num(beat_rna_t, 1000000)
tcga_rna_sum_mil = norm_utils.sum_gene_exp_to_num(tcga_rna_t, 1000000)

In [ ]:
for i in range(1, 5):
    print(beat_rna_sum_mil.iloc[:, i].sum())
beat_rna_sum_mil.head()

999999.9999999999
1000000.0
999999.9999999998
999999.9999999998

,SampleID,TSPAN6,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,RP11-218F10.3,RP11-686O6.2,RP11-313P22.1,RP11-548H3.1,RP11-102N12.3,RP11-196O16.1,RP4-671G15.2,RP11-731C17.2,RP4-621B10.8,RP11-114I8.4
0,12-00066,782.280658,3928.460512,2631.811003,4890.622319,13171.110842,1509.054705,4782.055886,4736.174239,4719.859026,...,3404.046892,1028.460342,6222.807809,4159.066758,2920.514651,2091.759272,4357.962441,2713.258672,1218.846544,4698.972070
1,12-00150,19045.431120,5415.896716,4442.475018,4945.485352,711.787276,2630.729376,9225.063571,4202.666812,2633.935959,...,986.607618,4590.470489,4208.352442,3610.706840,20540.851524,7167.368781,0.000000,1309.239554,0.000000,1430.016648
2,12-00211,0.000000,4232.818530,9410.359206,5511.482467,1624.395555,674.475999,6442.860166,7193.827260,6366.238987,...,10479.359688,2216.280894,3973.286339,5650.826929,932.379822,6455.381692,2782.575493,5478.211733,12840.929183,13501.401535
3,12-00258,0.000000,4946.370325,3910.097804,3599.238881,14589.692844,9680.377089,3273.978302,4701.004690,4247.850883,...,1986.473121,6068.391495,3765.891595,7287.494053,7953.409235,2320.783156,2637.332637,1997.024604,13277.091909,1866.180325
4,12-00294,0.000000,5264.722598,9792.826721,8294.658012,3890.545105,760.347083,4070.574070,6027.416860,4935.557470,...,13593.664813,1437.462807,6764.738073,6128.499529,5896.160529,216.564367,9474.975075,9839.426285,28392.710053,7388.639095

In [ ]:
for i in range(1, 5):
    print(tcga_rna_sum_mil.iloc[:, i].sum())
tcga_rna_sum_mil.head()

1000000.0000000002
1000000.0000000001
999999.9999999998
1000000.0

,SampleID,A1BG,A1CF,A2BP1,A2LD1,A2M,A2ML1,A4GALT,A4GNT,AAA1,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
0,TCGA.AB.2803,12028.095113,0.0,0.0,6236.388040,17992.509528,1415.860372,889.397454,0.000000,0.0,...,3914.350218,2193.918529,2381.305418,4550.739325,5146.571926,20103.701976,5411.828400,2940.613175,3576.698393,4912.848385
1,TCGA.AB.2805,2899.139627,0.0,0.0,4971.757645,725.654498,2700.487684,61.681535,9349.170162,0.0,...,6390.988936,3919.468694,1021.926445,4207.369301,7126.695658,4090.064997,10162.946941,4448.811282,6449.057638,5503.261785
2,TCGA.AB.2806,5999.413196,0.0,0.0,4879.830578,296.477830,4333.086034,1539.654893,4167.067712,0.0,...,7892.170491,4314.524147,5364.572024,9143.693570,6343.363241,2734.434914,4022.249561,3944.638045,5813.178851,8754.075388
3,TCGA.AB.2807,10417.707305,0.0,0.0,4119.605270,13647.025197,704.527567,9414.864794,15244.734930,0.0,...,6534.145229,6614.084012,11331.375388,9460.472274,4021.485281,6669.250388,6076.180166,2397.732016,6237.864515,5887.459966
4,TCGA.AB.2808,4527.088898,0.0,0.0,4850.851485,11617.584099,4459.077283,16878.959712,2756.497816,0.0,...,10223.983505,8093.936048,3414.997789,6016.342762,5495.885115,2411.972975,9106.327209,2805.208048,4897.424405,6911.573656

# Test gene_exp_log_trans

In [6]:
# beat_rna_log_1 = norm_utils.gene_exp_log_trans(beat_rna, 1)
beat_rna_log_mill = norm_utils.gene_exp_log_trans(beat_rna)

# tcga_rna_log_1 = norm_utils.gene_exp_log_trans(tcga_rna_sum_1, 1)
tcga_rna_log_mill = norm_utils.gene_exp_log_trans(tcga_rna)

In [7]:
beat_rna_log_mill.describe()

,12-00066,12-00150,12-00211,12-00258,12-00294,12-00372,13-00028,13-00034,13-00098,13-00118,...,16-01102,16-01138,16-01151,16-01185,16-01216,16-01219,16-01227,16-01237,16-01262,16-01270
count,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,...,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000
mean,4.502278,4.550235,4.604138,4.511846,4.627829,4.634766,4.585707,4.483837,4.517692,4.620302,...,4.402114,4.563525,4.540513,4.585009,4.511936,4.539782,4.338051,4.400741,4.489598,4.482292
std,1.461482,1.474066,1.481136,1.471452,1.486197,1.487081,1.503442,1.459746,1.468353,1.484146,...,1.446842,1.458575,1.448885,1.458454,1.461165,1.450529,1.341473,1.385008,1.454593,1.431740
min,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,...,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928
25%,3.366807,3.378355,3.383651,3.362726,3.386532,3.398746,3.363897,3.358336,3.380614,3.383335,...,3.354545,3.390003,3.389014,3.391309,3.396547,3.382131,3.370055,3.366949,3.357355,3.369062
50%,3.796695,3.863796,3.930304,3.795773,3.968950,3.988405,3.861460,3.763197,3.825918,3.957623,...,3.655719,3.899394,3.866054,3.935094,3.838508,3.854004,3.700039,3.746195,3.752796,3.818239
75%,5.305991,5.411602,5.558311,5.337541,5.602919,5.570895,5.541492,5.321456,5.318023,5.586398,...,5.088978,5.442595,5.400813,5.491182,5.252442,5.424226,4.945760,5.077350,5.352697,5.270199
max,14.167628,13.095665,13.883685,14.617816,13.780309,13.042565,13.714245,15.431696,13.417796,13.601699,...,14.089663,14.271403,14.040892,13.906285,13.696826,14.293059,15.364359,15.073984,15.373026,13.731219

In [8]:
beat_rna.describe()

,12-00066,12-00150,12-00211,12-00258,12-00294,12-00372,13-00028,13-00034,13-00098,13-00118,...,16-01102,16-01138,16-01151,16-01185,16-01216,16-01219,16-01227,16-01237,16-01262,16-01270
count,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,...,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000,22843.000000
mean,43.777087,43.777087,43.777087,43.777087,43.777087,43.777087,43.777087,43.777087,43.777087,43.777087,...,43.777087,43.777087,43.777087,43.777087,43.777087,43.777087,43.777087,43.777087,43.777087,43.777087
std,239.036200,179.037496,199.633444,255.030349,188.159584,165.383966,181.704322,357.619163,204.698390,190.984151,...,287.677166,262.096631,261.028608,229.596117,215.486602,290.598365,498.113439,430.670074,364.906680,272.110655
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.315968,0.398874,0.437118,0.286824,0.457980,0.546894,0.295178,0.255570,0.415165,0.434832,...,0.228660,0.483167,0.475986,0.492663,0.530827,0.426122,0.339214,0.316984,0.248603,0.332105
50%,3.896938,4.558558,5.245415,3.888061,5.659323,5.871919,4.535010,3.577982,4.181302,5.536860,...,2.603211,4.922261,4.581367,5.296126,4.305597,4.460082,2.996389,3.418903,3.480439,4.106020
75%,29.560559,32.565199,37.121401,30.435231,38.601161,37.534227,36.575262,29.986899,29.891861,38.047793,...,24.035727,33.489496,32.248063,34.979063,28.119088,32.939266,20.819249,23.762511,30.862263,28.591181
max,18392.670950,8743.627777,15104.913180,25132.075360,14059.753090,8427.297469,13429.990780,44188.081700,10933.570860,12421.379490,...,17424.573900,19765.174310,16845.031580,15343.553510,13268.700230,20064.259830,42172.561690,34482.244890,42426.733510,13589.053420

In [9]:
tcga_rna_log_mill.describe()

,TCGA.AB.2803,TCGA.AB.2805,TCGA.AB.2806,TCGA.AB.2807,TCGA.AB.2808,TCGA.AB.2810,TCGA.AB.2811,TCGA.AB.2812,TCGA.AB.2813,TCGA.AB.2814,...,TCGA.AB.3000,TCGA.AB.3001,TCGA.AB.3002,TCGA.AB.3005,TCGA.AB.3006,TCGA.AB.3007,TCGA.AB.3008,TCGA.AB.3009,TCGA.AB.3011,TCGA.AB.3012
count,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,...,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000
mean,4.616133,4.686806,4.672909,4.704069,4.715985,4.609821,4.538498,4.695363,4.670153,4.716283,...,4.712688,4.700445,4.698220,4.679289,4.754244,4.710427,4.714786,4.740185,4.753938,4.671815
std,1.515398,1.579850,1.573982,1.544839,1.576896,1.524506,1.539052,1.574276,1.548933,1.563662,...,1.567740,1.519055,1.559554,1.532947,1.569626,1.527757,1.567456,1.570722,1.567626,1.523582
min,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,...,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928,3.321928
25%,3.329747,3.327897,3.332554,3.352808,3.335970,3.331857,3.329074,3.329755,3.340901,3.336102,...,3.334456,3.350515,3.345333,3.337339,3.340805,3.334963,3.339164,3.345897,3.341572,3.342572
50%,3.993106,4.015947,3.976354,4.148485,4.091010,3.962895,3.804492,4.065733,4.047083,4.149780,...,4.107578,4.202060,4.094870,4.090463,4.217691,4.215432,4.108652,4.173217,4.214768,4.124843
75%,5.604074,5.759077,5.732523,5.698152,5.805259,5.563513,5.394920,5.776825,5.665997,5.796181,...,5.791668,5.687253,5.740962,5.704657,5.866546,5.754173,5.781137,5.843208,5.860948,5.648510
max,14.925199,13.862681,14.039958,14.018325,14.132621,14.539830,13.181880,14.596513,14.538785,14.253012,...,14.349901,15.015902,13.972469,14.429779,13.402986,15.539273,13.569962,14.389890,13.485712,15.464290

In [10]:
tcga_rna.describe()

,TCGA.AB.2803,TCGA.AB.2805,TCGA.AB.2806,TCGA.AB.2807,TCGA.AB.2808,TCGA.AB.2810,TCGA.AB.2811,TCGA.AB.2812,TCGA.AB.2813,TCGA.AB.2814,...,TCGA.AB.3000,TCGA.AB.3001,TCGA.AB.3002,TCGA.AB.3005,TCGA.AB.3006,TCGA.AB.3007,TCGA.AB.3008,TCGA.AB.3009,TCGA.AB.3011,TCGA.AB.3012
count,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,...,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000
mean,49.307233,49.307233,49.307233,49.307233,49.307233,49.307233,49.307233,49.307233,49.307233,49.307233,...,49.307233,49.307233,49.307233,49.307233,49.307233,49.307233,49.307233,49.307233,49.307233,49.307233
std,358.799961,209.351193,218.698925,206.815311,205.849947,287.885241,225.090745,226.113663,255.202582,207.832534,...,229.467962,300.174525,200.193958,283.727885,165.033426,377.413131,185.934475,223.882426,175.503445,362.606321
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.054346,0.041459,0.073922,0.216349,0.097804,0.069060,0.049653,0.054399,0.132379,0.098733,...,0.087212,0.200128,0.163555,0.107393,0.131703,0.090760,0.120189,0.167525,0.137092,0.144121
50%,5.923727,6.177840,5.739898,7.734474,7.041845,5.593743,3.972241,6.745870,6.530786,7.750404,...,7.238687,8.405442,7.087504,7.035393,8.605932,8.576830,7.251526,8.041124,8.568273,7.446223
75%,38.640096,44.157024,43.169368,41.917593,45.918709,37.291625,32.075839,44.827399,40.773274,45.567933,...,45.394408,41.526884,43.481280,42.152215,48.345366,43.973272,44.991527,47.409129,48.119418,40.161565
max,31102.325930,14886.446200,16834.131269,16583.430457,17951.505705,23809.083301,9282.684726,24763.554555,23791.832462,19514.687004,...,20870.968653,33121.192015,16064.310089,22059.697046,10821.807534,47609.757393,12150.892685,21457.852317,11461.069919,45197.999021

# Test ic50_log_trans

In [11]:
beat_drug_df = data_prep_utils.get_df("beat_drug")
beat_drug_df.head()

,12-00066,12-00150,12-00211,12-00258,12-00294,12-00372,13-00028,13-00034,13-00098,13-00118,...,16-01102,16-01138,16-01151,16-01185,16-01216,16-01219,16-01227,16-01237,16-01262,16-01270
A-674563,0.302313,0.183573,10.0,2.250759,0.312102,1.112644,3.699257,1.522665,5.132768,1.83987,...,0.726144,0.454933,0.103835,0.192891,0.515219,0.531155,1.261865,0.674077,0.518016,0.259479
Afatinib (BIBW-2992),0.270839,0.095105,10.0,1.042656,0.412103,0.492191,1.126676,0.313330,4.442185,1.09213,...,1.146014,1.047075,0.556972,0.615777,0.456265,0.809377,1.279045,0.983270,2.017039,1.303088
Alisertib (MLN8237),2.292925,10.000000,10.0,10.000000,1.731348,6.149094,10.000000,10.000000,10.000000,10.00000,...,10.000000,10.000000,2.080804,8.928137,6.927002,9.425326,4.785701,10.000000,10.000000,10.000000
Axitinib (AG-013736),0.137656,10.000000,10.0,10.000000,0.124162,10.000000,10.000000,10.000000,10.000000,10.00000,...,10.000000,10.000000,10.000000,10.000000,0.418123,10.000000,10.000000,10.000000,10.000000,0.299026
AZD1480,2.429158,NaN,10.0,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.00000,...,10.000000,6.874162,10.000000,10.000000,3.607693,7.004078,10.000000,10.000000,10.000000,10.000000

In [12]:
beat_drug_log = norm_utils.ic50_log_trans(beat_drug_df)

In [13]:
beat_drug_log.describe()

,12-00066,12-00150,12-00211,12-00258,12-00294,12-00372,13-00028,13-00034,13-00098,13-00118,...,16-01102,16-01138,16-01151,16-01185,16-01216,16-01219,16-01227,16-01237,16-01262,16-01270
count,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,...,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000
mean,-0.226548,0.543510,0.818007,0.710352,-0.077377,0.467910,0.625848,0.554665,0.792854,0.796274,...,0.796292,0.576881,0.420331,0.476224,-0.095549,0.717756,0.688047,0.673211,0.793150,0.194743
std,1.030967,0.754165,0.499345,0.534819,0.906244,0.737821,0.564817,0.746492,0.517604,0.397184,...,0.475184,0.658229,0.805154,0.729201,0.928227,0.479753,0.649592,0.560568,0.476364,0.793776
min,-2.853872,-2.163739,-1.862741,-1.862741,-2.225237,-1.862741,-1.862741,-1.862741,-2.163739,-0.723309,...,-1.188067,-1.862741,-1.908037,-1.862741,-2.567729,-1.012221,-1.862741,-1.368717,-0.953821,-1.975389
25%,-0.898967,0.273789,1.000000,0.590368,-0.605360,0.023178,0.337051,0.166441,1.000000,0.853099,...,0.985717,0.360666,-0.029656,0.000000,-0.634635,0.508658,0.735769,0.625523,1.000000,-0.317926
50%,-0.350197,1.000000,1.000000,1.000000,-0.046818,0.854859,1.000000,1.000000,1.000000,1.000000,...,1.000000,0.961467,1.000000,1.000000,-0.121266,1.000000,1.000000,1.000000,1.000000,0.264962
75%,1.000000,1.000000,1.000000,1.000000,0.850957,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.842322,1.000000,1.000000,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000